app = "flight-scraper"  # ← this must match your Fly.io app name exactly

[env]
PORT = "3000"

[http_service]
internal_port = 3000
force_https = true
auto_stop_machines = true
auto_start_machines = true